AnimalFarmsMarket/AnimalFarmsMarket.Core/Controllers/MarketController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

using AnimalFarmsMarket.Commons;
using AnimalFarmsMarket.Data.DTOs;
using AnimalFarmsMarket.Data.Models;
using AnimalFarmsMarket.Data.ViewModels;

using AutoMapper;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

using Newtonsoft.Json;

namespace AnimalFarmsMarket.Core.Controllers
{
    public class MarketController : Controller
    {
        private readonly IConfiguration _config;
        private readonly IMapper _mapper;

        public MarketController(IMapper mapper, IConfiguration config)
        {
            _config = config;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> Index(int page, string location, bool check)
        {
            var baseUrl = UrlHelper.BaseAddress(HttpContext);
            var localMarketDataToReturn = new PagedLivestockInfoVm();

            if (!string.IsNullOrEmpty(location))
            {
                var (LocalMarketResponse, LocalMarketData1) = await HttpHelper.GetContentAsync(baseUrl, "", "", "/api/v1/LiveStock/get-livestocks-by-location/?page=" + page + "&location=" + location);

                if (!LocalMarketData1.IsSuccessStatusCode)
                {
                    var ErrorData = JsonConvert.DeserializeObject<ResponseDto<PaginatedResultDto<string>>>(LocalMarketResponse);
                    ViewData["errorLocation"] = location;
                    ViewData["error"] = ErrorData.Message.ToString();
                }

                var LocalMarketData = JsonConvert.DeserializeObject<ResponseDto<PaginatedResultDto<ShapedListOfLivestockVm>>>(LocalMarketResponse);
                if (LocalMarketData.Data != null)
                {
                    localMarketDataToReturn = new PagedLivestockInfoVm
                    {
                        PageMetaData = LocalMarketData.Data.PageMetaData,
                        ResponseData = LocalMarketData.Data.ResponseData
                    };
                }
            }

            /// section to get location and market
            var res = await SideNavMethod(baseUrl, localMarketDataToReturn, location);

            //-------------------------------------------------------------------------------------------

            if (string.IsNullOrEmpty(location))
            {
                ViewData["Location"] = location;
                return View(res);
            }

            ViewData["Location"] = location;
            ViewData["route"] = "Location";
            return View(res);
        }

        [HttpGet]
        [ActionName("fetchLivestockLocation-market")]
        public async Task<IActionResult> Index(int page, string location, string market)
        {
            var baseUrl = UrlHelper.BaseAddress(HttpContext);
            var MarketDataToReturn = new PagedLivestockInfoVm();
            if (string.IsNullOrEmpty(location) && (string.IsNullOrEmpty(market)))
            {
                ViewData["Location"] = location;
                ViewData["errorLocation"] = location;
                return View();
            }

            if (!string.IsNullOrEmpty(location) && (!string.IsNullOrEmpty(market)))
            {
                var (MarketResponse, MarketData) = await HttpHelper.GetContentAsync(baseUrl, "", "",
                    "/api/v1/LiveStock/get-livestocks-by-location-and-market?page=" + page + "&location=" + location + "&market=" + market);

                if (!MarketData.IsSuccessStatusCode)
                {
                    var ErrorData = JsonConvert.DeserializeObject<ResponseDto<PaginatedResultDto<string>>>(MarketResponse);
                    ViewData["erorLocation"] = location;
                    ViewData["error"] = ErrorData.Message.ToString();
                }

                var myMarketData = JsonConvert.DeserializeObject<ResponseDto<PaginatedResultDto<ShapedListOfLivestockVm>>>(MarketResponse);
                if (myMarketData.Data != null)
                {
                    MarketDataToReturn = new PagedLivestockInfoVm
                    {
                        PageMetaData = myMarketData.Data.PageMetaData,
                        ResponseData = myMarketData.Data.ResponseData
                    };
                }
            }

            /// section to get location and market
            var res = await SideNavMethod(baseUrl, MarketDataToReturn, location);

            ViewData["Location"] = location;
            ViewData["route"] = "LocationMarket";
            ViewBag.Market = market;
            return View("Index", res);
        }

        [HttpGet]
        [ActionName("Index-fetchAll")]
        public async Task<IActionResult> Index(int page, string location)
        {
            var baseUrl = UrlHelper.BaseAddress(HttpContext);
            var localMarketDataToReturn = new PagedLivestockInfoVm();

            var (respo, response) = await HttpHelper.GetContentWithoutTokenAsync(baseUrl, "", "/api/v1/LiveStock/get-livestocks/?page=" + page);
            if (!response.IsSuccessStatusCode)
            {
                return RedirectToAction("PageNotFoundHandler", "Error", new { StatusCode = response.StatusCode });
            }

            var content = JsonConvert.DeserializeObject<ResponseDto<PaginatedResultDto<ShapedListOfLivestockVm>>>(respo);
            if (content.Data != null)
            {
                localMarketDataToReturn = new PagedLivestockInfoVm
                {
                    PageMetaData = content.Data.PageMetaData,
                    ResponseData = content.Data.ResponseData
                };
            }
            // section to get location and market
            var res = await SideNavMethod(baseUrl, localMarketDataToReturn, location);
            ViewData["Location"] = "All Market";
            ViewData["route"] = "all";
            return View("Index", res);
        }

        [HttpGet]
        [ActionName("IndexByQuery")]
        public async Task<IActionResult> Index(string type, byte sex, decimal weight, string breed, int page, string lvstckLocation)
        {
            var baseUrl = UrlHelper.BaseAddress(HttpContext);
            var MarketDataToReturn = new PagedLivestockInfoVm();

            /// if user clicks both search buttons with selecting a parameter
            if (string.IsNullOrEmpty(type) && string.IsNullOrEmpty(breed) && weight == 0 && lvstckLocation == null)
            {
                /// section to get location and market
                var res = await SideNavMethod(baseUrl, MarketDataToReturn, lvstckLocation);

                ViewData["Location"] = lvstckLocation;
                ViewData["errorLocation"] = lvstckLocation;
                return View("Index", res);
            }
            if (!string.IsNullOrEmpty(type) && string.IsNullOrEmpty(breed) && weight == 0 && lvstckLocation == null)
            {
                /// section to get location and market
                var res = await SideNavMethod(baseUrl, MarketDataToReturn, lvstckLocation);

                ViewData["Location"] = lvstckLocation;
                ViewData["errorLocation"] = lvstckLocation;
                return View("Index", res);
            }

            var (modelResponse1, modelResponse2) = await HttpHelper.GetContentWithoutTokenAsync(baseUrl, "",
                "/api/v1/LiveStock/get-livestocks-by-search-term?" + $"Type={type}&Sex={sex}&Weight={weight}&Breed={breed}&PageNumber={page}");

            if (!modelResponse2.IsSuccessStatusCode)
            {
                var ErrorData = JsonConvert.DeserializeObject<ResponseDto<PaginatedResultDto<string>>>(modelResponse1);
                var res = await SideNavMethod(baseUrl, MarketDataToReturn, lvstckLocation);
                ViewData["errorLocation"] = lvstckLocation;
                ViewData["error"] = ErrorData.Message.ToString();
                return View("Index", res);
            }

            var modelData = JsonConvert.DeserializeObject<ResponseDto<PaginatedResultDto<ShapedListOfLivestockVm>>>(modelResponse1);
            if (modelData.Data != null)
            {
                MarketDataToReturn = new PagedLivestockInfoVm
                {
                    PageMetaData = modelData.Data.PageMetaData,
                    ResponseData = modelData.Data.ResponseData
                };
            }

            var myRes = await SideNavMethod(baseUrl, MarketDataToReturn, lvstckLocation);
            ViewData["Location"] = lvstckLocation;
            ViewBag.Market = type + " Market";
            return View("Index", myRes);
        }

        [HttpGet]
        public async Task<IActionResult> GetLivestockByMarket(string market)
        {
            if (string.IsNullOrEmpty(market))
            {
                return View();
            }

            var baseUrl = UrlHelper.BaseAddress(HttpContext);
            var (MarketResponse, MarketData1) = await HttpHelper.GetContentAsync(baseUrl, "", "", "/api/v1/LiveStock/get-livestocks-by-location/?page=" + market);

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Details(string id)
        {
            var details = new DetailsViewModel();
            var baseUrl = UrlHelper.BaseAddress(HttpContext);
            var res = await LivestockLoad(baseUrl, id);
            if (res == null)
            {
                return RedirectToAction("PageNotFoundHandler", "Error", new { StatusCode = 404 });
            }

            details.LivestockModel = res;
            return View(details);
        }

        //Get distinct fields data for a category in JSON format
        [HttpGet]
        public async Task<IActionResult> GetDataForLivestockCategory(string livestockCategory)
        {
            var baseUrl = UrlHelper.BaseAddress(HttpContext);

AnimalFarmsMarket/AnimalFarmsMarket.Core/Views/Shared/AccessDenied.cshtml
@{
    ViewData["Title"] = "Access Denied";
}


<section id="error" class="container text-center" style="padding-top:30px; padding-bottom:30px">
    <h1>401, Access Denied</h1>
    <p>You do not have acess to view this page...Ensure your email is confirmed</p>
    <a class="btn btn-primary" asp-action="Index" asp-controller="Home">GO BACK TO THE HOMEPAGE</a>
</section><!--/#error-->

AnimalFarmsMarket/AnimalFarmsMarket.Core/Views/Shared/NotFound.cshtml
@{
    ViewData["Title"] = "Not found";
}


<section id="error" class="container text-center" style="padding-top:30px; padding-bottom:30px">
    <h1>404, Page not found</h1>
    <p>The Page you are looking for doesn't exist or is moved to another location.</p>
    <a class="btn btn-primary" asp-action="Index" asp-controller="Home">GO BACK TO THE HOMEPAGE</a>
</section><!--/#error-->

AnimalFarmsMarket/AnimalFarmsMarket.Core/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" href="~/css/owl-carousel/owl.carousel.min.css"/>
    <link rel="stylesheet" href="~/css/owl-carousel/owl.theme.default.min.css"/>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
    <link rel="stylesheet" href="~/css/Market.css"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/modals.css" />
    <link rel="stylesheet" href="~/css/sliders.css" />
    <link rel="stylesheet" href="~/css/DetailsPage.css"/>
    <link rel="stylesheet" href="~/css/homePartial.css" />
    <link href="~/css/partner.css" rel="stylesheet" />
    <link href="~/css/about-us.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
    <script>var currentUser = '@HttpContextAccessor.HttpContext.Session.GetString("UserId")';</script>
    <script src="https://www.gstatic.com/firebasejs/3.1.0/firebase.js"></script>
    <script src="~/js/cart.js"></script>
</head>
<body class=" bg-light">
    <header>
        <nav class="home-nav d-flex justify-content-between align-items-center">
            <div class="container d-flex justify-content-between align-items-center">

                <div class="logo-div">
                    <a asp-action="index" asp-controller="home">
                        <img src="~/images/assets/footer-logo.png" alt="live stock delivery" />
                    </a>
                </div>

                <div class="menu-div">
                    <div class="hamburger-div">
                        <i class="fa fa-navicon fa-2x text-white"></i>
                    </div>
                    <div class="menu-list-div">
                        <div class="menu-dropdown-div dropdown-menu-container">
                            <div class="menu-list-items">
                                <ul class="navbar-nav align-items-center justify-content-around w-100">
                                    <li class="nav-item dropdown dropdown-element">
                                        <a class="nav-link pad-home-nav" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                    </li>
                                    <li class="nav-item dropdown dropdown-element nav-item">
                                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="AboutUs">About Us</a>
                                    </li>
                                    <li class="nav-item dropdown dropdown-element nav-item">
                                        <a class="nav-link" asp-area="" asp-controller="Account" asp-action="AboutAgent">Be an Agent</a>
                                    </li>
                                    <li class="nav-item dropdown dropdown-element nav-item">
                                        <a class="nav-link pad-home-nav" data-toggle="modal" id="testcreate-agent__btn" data-target="#track" href="">Track Livestock</a>
                                    </li>

                                </ul>
                            </div>
                            <div class="loggedin-user-div">
                                <button id="locationModalBtn" class="text-light button-primary btn shadow buy-now-btn">Buy Now</button>
                                @if (!User.Identity.IsAuthenticated)
                                {
                                    <form asp-action="Login" asp-controller="Account" method="get">
                                        <button type="submit" class="text-light button-secondary btn shadow login-nav-btn">Login</button>
                                    </form>
                                }
                                else
                                {
                                    <partial name="_UserNavThumbnailPartial" />
                                }
                            </div>
                        </div>
                    </div>
                </div>

                <div class="drop">
                    <a href="#" class="pull-cart">
                        <i class="bi bi-cart2" style="font-size:28px; color:#fff;"></i>
                        <span id="shoppingCart-badge" class="badge badge-light rounded-circle"
                              style="font-size:10px;color:#2078bf; margin-left:-1em;top:-2em;">0</span>
                    </a>
                    <div class="dropdown-content">
                        <div class="menu-cart-cover">
                            <div id="menu-cart">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
    </header> 

    <div class="body-con">
        <div class="modal fade" id="track" role="dialog" aria-labelledby="track" aria-hidden="true" style="z-index:99999;">
            <div class="modal-dialog  modal-lg" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h3 class="text-center font-weight-bold w-100 text-center modal-title">Track Your Item</h3>
                        <button id="playCarousel" type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="col-sm-12 d-flex rounded">
                            <div class="col-12">
                                <p class="text-center px-3">Please fill in the tracking ID provided during purchase.</p>
                                <div asp-validation-summary="ModelOnly"></div>
                                <div class="row">
                                    <div class="col-sm-6 m-sm-auto">
                                        <input id="trackingIndex" type="text" class="w-100" />
                                    </div>
                                </div>
                                <div class="text-center">
                                    <button onclick="TrackingBtn1(this)" class="btn btn-primary mt-3"
                                            id="create-agent__btn">
                                        Track
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade" id="trackingHistory" role="dialog" aria-labelledby="trackingHistory" aria-hidden="true" style="z-index:999999;">
            <div class="modal-dialog  modal-lg" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h3 class="text-center font-weight-bold w-100 text-center modal-title">Order Information</h3>
                        <button id="playCarousel" type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body overflow-auto">

                        <div asp-validation-summary="ModelOnly"></div>
                        <div class="justify-content-lg-start" style="margin-top:20px" id="trackingHistoryPage">
                            <div id="trackingHistory1">

                            </div>
                        </div>


                    </div>
                </div>
            </div>
        </div>
        @RenderBody()

    </div>

    <!-- Locations Modal -->
    <div class="modal fade" id="preferredLocationModal" tabindex="-1" role="dialog" aria-labelledby="preferredLocation" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
            <div class="modal-content">
                <button type="button" class="close text-right pr-3" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <div class="modal-body">
                    <form asp-controller="Market" asp-action="Index" method="GET">
                        <input name="page" id="page" type="hidden" value="1" />
                        <input name="location" id="location" type="hidden" value="" />
                        <div id="" class="px-5 py-3 text-center">
                            <h3 class="site-color"><b><span>Choose your preferred</span> location</b></h3><br>
                            <h5 class="site-color">This displays all products associated with the chosen address</h5><br>
                            <div class="dropdown-container modal-dropdown-container">
                                <div class="dropdown modal-dropdown w-75 bg-white">
                                    <button class="btn btn-light text-left w-100" type="button" data-toggle="dropdown">
                                        <span class="pl-2 dropdown-text text-grey">Location</span>
                                        <span class="caret float-right">
                                            <i class="fa fa-caret-down" aria-hidden="true"></i>
                                        </span>
                                    </button>
                                    <ul id="locations-list" class="dropdown-menu mt-0 w-100" style="overflow-y:auto; max-height:150px;">
                                    </ul>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-green text-white mt-70px" id="ctn" style="width:150px;">Continue</button>
                        </div><br><br>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Cart Modal container. Javascript was used to fill the content -->
    <div class="modal fade mx-0" id="cartModal" tabindex="-1" style="z-index:12000!important" role="dialog" aria-labelledby="cart" aria-hidden="true">
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/owl-carousel/owl.carousel.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/popper/popper.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/MarketPlaceScript.js" asp-append-version="true"></script>
    <script src="~/js/Market.js" asp-append-version="true"></script>
    <script src="~/js/modals.js" asp-append-version="true"></script>
    <script src="~/js/scrollers.js" asp-append-version="true"></script>
    <script src="~/js/DetailsPage.js" asp-append-version="true"></script>
    <script src="~/js/TrackingHistory.js" asp-append-version="true"></script>

    
    <script>
        $(document).ready(function () {
            // Add down arrow icon for collapse element which is open by default
            $(".collapse.show").each(function () {
                $(this).prev(".heading").find(".fa").addClass("fa-angle-down").removeClass("fa-angle-right");
            });
            // Toggle right and down arrow icon on show hide of collapse element
            $(".collapse").on('show.bs.collapse', function () {
                $(this).prev(".heading").find(".fa").removeClass("fa-angle-right").addClass("fa-angle-down");
            }).on('hide.bs.collapse', function () {
                $(this).prev(".heading").find(".fa").removeClass("fa-angle-down").addClass("fa-angle-right");
            });
            updateShoppingCart();
            setInterval(updateShoppingCart, 5000);
            fillCartTable();
            setInterval(UpdateCheckoutPage, 2000);
        });</script>
    @RenderSection("Scripts", required: false)
</body>
</html>

AnimalFarmsMarket/AnimalFarmsMarket.Core/Views/Shared/_LocationPartial.cshtml
@model IEnumerable<LocationMarketVm>

@{
    Object shouldRender = null;
    if (Model == null)
    {
        shouldRender = "";
    }
}
<nav class="navbar navbar-expand-sm navbar-toggleable-sm m-0 p-0">
    <div class="p-0 m-0 w-100">
        <div class="toggle-btn-close">
            <button class="navbar-toggler toggleColor mt-3" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false" aria-controls="navbarSupportedContent"
                    aria-label="Toggle navigation">
                <i class="fa fa-compass fa-2x"></i>
                Market Menu
            </button>
            <i id="close-button" class="fa fa-close" style="position:absolute; font-size:30px; top: 10px; right:20px; cursor:pointer; color:red; z-index: 2000;"></i>
        </div>

        <div class="navbar-collapse collapse d-sm-inline-flex">
            <div class="row w-100 mt-3">
                <div class="col-lg-12">
                    <div class="accordion box-shadow" id="accordionFlushExample">

                        @if (shouldRender == "")
                        {
                            <div class="myaccordion ">
                                <div class="heading" id="header">
                                    <h2 class="mb-0" id="flush-headingOne">
                                        <button class="d-flex btn accordion-btn accordion-active text-left collapsed w-100 " type="button" data-toggle="collapse" data-target="#flush-collapseOne" aria-expanded="true" aria-controls="flush-collapseOne">
                                            Lagos <i class="fa fa-angle-down ml-auto p-1"></i>
                                        </button>
                                    </h2>
                                </div>

                                <div id="flush-collapseOne" class="collapse" aria-labelledby="flush-headingOne" data-parent="#accordionFlushExample">

                                    <div>
                                        <ul class="list-group">
                                            <li class="list-group-item border-0 text-secondary" style="cursor:pointer">
                                                <a style="text-decoration:none" asp-action="fetchLivestockLocation-market" asp-controller="Market" asp-route-market="Fish Market">
                                                    Fish Market  <span class="badge bg-warning float-right bg-info">5</span>
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="myaccordion ">
                                <div class="heading" id="header">
                                    <h2 class="mb-0" id="flush-headingTwo">
                                        <button class="d-flex btn accordion-btn accordion-active text-left collapsed w-100 " type="button" data-toggle="collapse" data-target="#flush-collapseTwo" aria-expanded="true" aria-controls="flush-collapseOne">
                                            Kano <i class="fa fa-angle-down ml-auto p-1"></i>
                                        </button>
                                    </h2>
                                </div>

                                <div id="flush-collapseTwo" class="collapse" aria-labelledby="flush-headingTwo" data-parent="#accordionFlushExample">

                                    <div>
                                        <ul class="list-group">
                                            <li class="list-group-item border-0 text-secondary" style="cursor:pointer">
                                                <a style="text-decoration:none" asp-action="fetchLivestockLocation-market" asp-controller="Market" asp-route-market="Sheep Market">
                                                    Sheep Market  <span class="badge bg-warning float-right bg-info">5</span>
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="myaccordion ">
                                <div class="heading" id="header">
                                    <h2 class="mb-0" id="flush-headingTri">
                                        <button class="d-flex btn accordion-btn accordion-active text-left collapsed w-100 " type="button" data-toggle="collapse" data-target="#flush-collapseTri" aria-expanded="true" aria-controls="flush-collapseOne">
                                            Enugu  <i class="fa fa-angle-down ml-auto p-1"></i>
                                        </button>
                                    </h2>
                                </div>

                                <div id="flush-collapseTri" class="collapse" aria-labelledby="flush-headingTri" data-parent="#accordionFlushExample">

                                    <div>
                                        <ul class="list-group">
                                            <li class="list-group-item border-0 text-secondary" style="cursor:pointer">
                                                <a style="text-decoration:none" asp-action="fetchLivestockLocation-market" asp-controller="Market" asp-route-market="Pig Market">
                                                    Pig Market  <span class="badge bg-warning float-right bg-info">2</span>
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div> }
                        else
                        {

                            @foreach (var item in @Model)
                            {

                                <div class="myaccordion ">
                                    <div class="heading" id="header">
                                        <h2 class="mb-0" id="flush-headingOne">
                                            <button class="d-flex btn accordion-btn accordion-active text-left collapsed w-100 " type="button" data-toggle="collapse" data-target="#flush-collapseOne_@item.location" aria-expanded="true" aria-controls="flush-collapseOne">
                                                @item.location<i class="fa fa-angle-down ml-auto p-1"></i>
                                            </button>
                                        </h2>
                                    </div>

                                    <div id="flush-collapseOne_@item.location" class="collapse" aria-labelledby="flush-headingOne" data-parent="#accordionFlushExample">

                                        <div>
                                            <ul class="list-group">
                                                @foreach (var market in @item.MarketData)
                                                {

                                                    <li class="list-group-item border-0 text-secondary" style="cursor:pointer">
                                                        <a style="text-decoration:none" asp-action="fetchLivestockLocation-market" asp-controller="Market" asp-route-market="@market.MarketName" asp-route-location="@item.location">
                                                            @market.MarketName <span class="badge bg-warning float-right bg-info">@market.NoOfLivestocks</span>
                                                        </a>
                                                    </li>
                                                }
                                            </ul>
                                        </div>
                                    </div>
                                </div>}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</nav>